baseurl = "https://fntlnz.wtf"
languageCode = "en-us"
title = "Lorenzo Fontana's Homepage"
theme = "fntlnz"
paginate = 500
pygmentsCodeFences = true
pygmentsStyle = "borland"
pygmentsCodeFencesGuessSyntax = false
publishDir = "docs"
enableGitInfo = true

[taxonomies]
    category = ""
    tag = ""
