baseurl = "https://fntlnz.wtf"
languageCode = "en-us"
title = "Lorenzo Fontana's Homepage"
theme = "fntlnz"
paginate = 500
PygmentsCodeFences = true
PygmentsOptions = ""
PygmentsStyle = "bw"
disqusShortname = "fntlnz"
googleAnalytics = "UA-45983436-3"

