baseurl = "https://fntlnz.wtf"
languageCode = "en-us"
title = "fntlnz"
theme = "hugo-classic"
enableEmoji = true
publishDir = "docs"
enableGitInfo = true
footnotereturnlinkcontents = "↩"

[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Just remember that you're awesome! :rainbow: | [Github](https://github.com/fntlnz) | [Twitter](https://twitter.com/fntlnz) | [GPG Key](/downloads/pubkey-B2400EE4.asc)"
